"""Nouveaux champs dans la talbe User

Revision ID: 4716e0e88f40
Revises: 1cd432f2bbe6
Create Date: 2023-02-09 09:37:31.502223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4716e0e88f40'
down_revision = '1cd432f2bbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
