"""Ajout des abonnements

Revision ID: 5d85b3c577af
Revises: 4716e0e88f40
Create Date: 2023-02-16 08:57:51.921779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d85b3c577af'
down_revision = '4716e0e88f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements',
    sa.Column('abonne_id', sa.Integer(), nullable=True),
    sa.Column('abonnement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abonne_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['abonnement_id'], ['user.id'], ),
    sa.UniqueConstraint('abonne_id', 'abonnement_id', name='unicite_couple')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abonnements')
    # ### end Alembic commands ###
